version: '3.9'

services:
    nginx:
        build: docker/nginx
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./var/log/nginx:/var/log/nginx/
        links:
            - php-fpm

    php-fpm:
        build: 
            context: docker/php-fpm
            args:
                - UID
                - GID
        volumes:
            - ./:/var/www/html
